import pandas as pd
from pymongo import MongoClient

# MongoDB连接信息
MONGO_URI = "mongodb://localhost:27017"
DB_NAME = "airport-management"
COLLECTION_NAME = "airlines"

# 城市代码到城市名称的映射表
city_code_to_name = {
    "BJS": "北京",
    "SHA": "上海",
    "CAN": "广州",
    "SZX": "深圳",
    "CTU": "成都",
    "HGH": "杭州",
    "WUH": "武汉",
    "SIA": "咸阳",
    "CKG": "重庆",
    "TAO": "青岛",
    "CSX": "长沙",
    "NKG": "南京",
    "XMN": "厦门",
    "KMG": "昆明",
    "DLC": "大连",
    "TSN": "天津",
    "CGO": "郑州",
    "SYX": "三亚",
    "TNA": "济南",
    "FOC": "福州",
    "AAT": "阿勒泰",
    "AKU": "阿克苏",
    "AOG": "鞍山",
    "AQG": "安庆",
    "AVA": "安顺",
    "AXF": "阿拉善左旗",
    "MFM": "中国澳门",
    "NGQ": "阿里",
    "RHT": "阿拉善右旗",
    "YIE": "阿尔山",
    "BZX": "巴中",
    "AEB": "百色",
    "BAV": "包头",
    "BFJ": "毕节",
    "BHY": "北海",
    "DAXING": "北京(大兴国际机场)",
    "CAPITAL": "北京(首都国际机场)",
    "BPL": "博乐",
    "BSD": "保山",
    "DBC": "白城",
    "KJI": "布尔津",
    "NBS": "白山",
    "RLK": "巴彦淖尔",
    "BPX": "昌都",
    "CDE": "承德",
    "CGD": "常德",
    "CGQ": "长春",
    "CHG": "朝阳",
    "CIF": "赤峰",
    "CIH": "长治",
    "CWJ": "沧源",
    "CZX": "常州",
    "JUH": "池州",
    "SWA": "汕头",
    "DAT": "大同",
    "DAX": "达州",
    "DCY": "稻城",
    "DDG": "丹东",
    "DIG": "香格里拉",
    "DLU": "大理",
    "DNH": "敦煌",
    "DOY": "东营",
    "DQA": "大庆",
    "HXD": "德令哈",
    "LUM": "芒市",
    "DSN": "鄂尔多斯",
    "EJN": "额济纳旗",
    "ENH": "恩施",
    "ERL": "二连浩特",
    "FUG": "阜阳",
    "FYJ": "抚远",
    "FYN": "富蕴",
    "GMQ": "果洛",
    "GOQ": "格尔木",
    "GYS": "广元",
    "GYU": "固原",
    "KHH": "中国高雄",
    "KOW": "赣州",
    "KWE": "贵阳",
    "KWL": "桂林",
    "AHJ": "红原",
    "HAK": "海口",
    "HCJ": "河池",
    "HDG": "邯郸",
    "HEK": "黑河",
    "HET": "呼和浩特",
    "HFE": "合肥",
    "HIA": "淮安",
    "HJJ": "芷江",
    "HLD": "海拉尔",
    "HMI": "哈密",
    "HNY": "衡阳",
    "HRB": "哈尔滨",
    "HTN": "和田",
    "HTT": "花土沟",
    "HUN": "中国花莲",
    "HUO": "霍林郭勒",
    "HUZ": "惠州",
    "HZG": "汉中",
    "TXN": "黄山",
    "XRQ": "呼伦贝尔",
    "CYI": "中国嘉义",
    "JDZ": "景德镇",
    "JGD": "加格达奇",
    "JGN": "嘉峪关",
    "JGS": "井冈山",
    "JHG": "西双版纳",
    "JIC": "金昌",
    "JIU": "九江",
    "JJN": "石狮",
    "JM1": "荆门",
    "JMU": "佳木斯",
    "JNG": "济宁",
    "JNZ": "锦州",
    "JSJ": "建三江",
    "JXA": "鸡西",
    "JZH": "九寨沟",
    "KNH": "中国金门",
    "KCA": "库车",
    "KGT": "康定",
    "KHG": "喀什",
    "KJH": "凯里",
    "KRL": "库尔勒",
    "KRY": "克拉玛依",
    "HZH": "黎平",
    "JMJ": "澜沧",
    "LCX": "龙岩",
    "LFQ": "临汾",
    "LHW": "兰州",
    "LJG": "丽江",
    "LLB": "荔波",
    "LLV": "吕梁",
    "LNJ": "临沧",
    "LNL": "陇南",
    "LPF": "六盘水",
    "LXA": "拉萨",
    "LYA": "洛阳",
    "LYG": "连云港",
    "LYI": "临沂",
    "LZH": "柳州",
    "LZO": "泸州",
    "LZY": "林芝",
    "MDG": "牡丹江",
    "MFK": "中国马祖",
    "MIG": "绵阳",
    "MXZ": "梅州",
    "MZG": "中国澎湖列岛",
    "NZH": "满洲里",
    "OHE": "漠河",
    "KHN": "南昌",
    "LZN": "中国南竿",
    "NAO": "南充",
    "NGB": "宁波",
    "NLH": "宁蒗",
    "NNG": "南宁",
    "NNY": "南阳",
    "NTG": "南通",
    "PZI": "攀枝花",
    "SYM": "普洱",
    "BAR": "琼海",
    "BPE": "秦皇岛",
    "HBQ": "祁连",
    "IQM": "且末",
    "IQN": "庆阳",
    "JIQ": "黔江",
    "JUZ": "衢州",
    "NDG": "齐齐哈尔",
    "RIZ": "日照",
    "RKZ": "日喀则",
    "RQA": "若羌",
    "HPG": "神农架",
    "QSZ": "莎车",
    "PU DONG": "上海(浦东国际机场)",
    "HONGQIAO": "上海(虹桥国际机场)",
    "SHE": "沈阳",
    "SHF": "石河子",
    "SJW": "石家庄",
    "SQD": "上饶",
    "SQJ": "三明",
    "WDS": "十堰",
    "WGN": "邵阳",
    "YSQ": "松原",
    "HYN": "台州",
    "RMQ": "中国台中",
    "TCG": "塔城",
    "TCZ": "腾冲",
    "TEN": "铜仁",
    "TGO": "通辽",
    "THQ": "天水",
    "TLQ": "吐鲁番",
    "TNH": "通化",
    "TNN": "中国台南",
    "TPE": "中国台北",
    "TTT": "中国台东",
    "TVS": "唐山",
    "TYN": "太原",
    "YTY": "扬州",
    "DTU": "五大连池",
    "HLH": "乌兰浩特",
    "UCB": "乌兰察布",
    "URC": "乌鲁木齐",
    "WEF": "潍坊",
    "WEH": "威海",
    "WNH": "文山",
    "WNZ": "温州",
    "WUA": "乌海",
    "WUS": "武夷山",
    "WUX": "无锡",
    "WUZ": "梧州",
    "WXN": "万州",
    "WZQ": "乌拉特中旗",
    "WSK": "巫山",
    "ACX": "兴义",
    "GXH": "夏河",
    "HKG": "中国香港",
    "NLT": "新源",
    "WUT": "忻州",
    "XAI": "信阳",
    "XFN": "襄阳",
    "XIC": "西昌",
    "XIL": "锡林浩特",
    "XNN": "西宁",
    "XUZ": "徐州",
    "ENY": "延安",
    "INC": "银川",
    "LDS": "伊春",
    "LLF": "永州",
    "UYN": "榆林",
    "YBP": "宜宾",
    "YCU": "运城",
    "YIC": "宜春",
    "YIH": "宜昌",
    "YIN": "伊宁",
    "YIW": "义乌",
    "YKH": "营口",
    "YNJ": "延吉",
    "YNT": "烟台",
    "YNZ": "盐城",
    "YUS": "玉树",
    "YYA": "岳阳",
    "DYG": "张家界",
    "HSN": "舟山",
    "NZL": "扎兰屯",
    "YZY": "张掖",
    "ZAT": "昭通",
    "ZHA": "湛江",
    "ZHY": "中卫",
    "ZQZ": "张家口",
    "ZUH": "珠海",
    "ZYI": "遵义"
}

def main():
    # 读取Excel文件
    excel_file = "携程航班数据-北京.xlsx"  # 替换为你的Excel文件路径
    df = pd.read_excel(excel_file)

    # 提取需要的列
    airlines_data = []

    for index, row in df.iterrows():
        # 提取周计划列（假设从第S列到Y列，即第19列到35列）
        week_plan = row[18:35].dropna().tolist()

        # 转换出发地和到达地的城市代码为城市名称
        depart_city_name = city_code_to_name.get(row["departCityCode"], "未知城市")
        arrive_city_name = city_code_to_name.get(row["arriveCityCode"], "未知城市")

        airline = {
            "numb": row["flightNo"],  # 航班号
            "type": row["aircraftType"],  # 机型
            "startTime": row["departTime"],  # 启航时间
            "startAirport": row["departPortName"],  # 启航机场
            "endTime": row["arriveTime"],  # 抵达时间
            "endAirport": row["arrivePortName"],  # 抵达机场
            "date": week_plan,  # 周计划
            "ontimeRate": row["onTimeRate"],  # 准时率
            "from": depart_city_name,  # 出发地
            "to": arrive_city_name,  # 到达地
            "price":row["price"]  # 票价
        }
        airlines_data.append(airline)

    # 连接MongoDB
    client = MongoClient(MONGO_URI)
    db = client[DB_NAME]
    collection = db[COLLECTION_NAME]

    # 将数据存入数据库
    collection.insert_many(airlines_data)

    print("航班数据已成功存入MongoDB数据库！")

if __name__ == "__main__":
    main()